### ISSUE TITLE
Написать ТЗ

### ISSUE THREAD

**Issue by rominf** [iu7-ray-teamwork/junkcraft#1]

**Comment by yuri-kilochek** [comment]
как его писать? шаблон у нас есть какойто?

**Comment by yuri-kilochek** [comment]
[Вот](https://github.com/iu7-ray-teamwork/junkcraft/wiki/%D0%A2%D0%97) что-то сделал. Если в течение суток не будет возражений  возражений то закрою issue.

**Comment by Alexey-Abakumkin** [comment]
Возможно следует добавить минимальные системные требования.

**Comment by yuri-kilochek** [comment]
У нас ничего требовательного нету, любой комп запустит. Будем пока считать что написано.

**Comment by Alexey-Abakumkin** [comment]
Необходимо добавить пункт "python3 с оконной системой" - в консольке же не взлетит у нас?

**Comment by yuri-kilochek** [comment]
Согласен, добавь.
