### ISSUE TITLE
Запилить матан.

### ISSUE THREAD

**Issue by yuri-kilochek** [iu7-ray-teamwork/junkcraft#17]
Запилить классы Matrix (3x2) и Vector (2D) ( Однородные (homogeneous) координаты). Нужно создание матриц поворота/перемещения/масштабирования, произведение матриц (как будто 3x3 с [0;0;1] в третьем столбце). Для векторов - сложение, вычитание, умножение/деление на скаляры, длина, длина в квадрате, нормализация, умножение на матрицу (как будто 3D с 1 в третьем элементе).

**Comment by rominf** [comment]
Ну нафига это самим делать-то? Велосипедописатели, блин. Надо было вообще Unity брать и делать как парень на Шаге делал.
Эх, ладно, проехали.

**Comment by yuri-kilochek** [comment]
@rominf В чужом коде, как известно, полно фатальных недостатков). Восновном в том что либы плохо друг с другом сочетаются и надо их оборачивать. Такие никоуровневые штуки проще самому запилить чем оборачивать другие.

**Comment by yuri-kilochek** [comment]
Закрыто #19
