### ISSUE TITLE
Оценить риски

### ISSUE THREAD

**Issue by rominf** [iu7-ray-teamwork/junkcraft#2]

**Comment by yuri-kilochek** [comment]
росинский нам презентации высылал с примерами таблиц рисков?

**Comment by Alexey-Abakumkin** [comment]
Вроде нет. Запрошу у него по почте

**Comment by Alexey-Abakumkin** [comment]
[готово](https://github.com/iu7-ray-teamwork/junkcraft/wiki/%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0-%D0%A0%D0%B8%D1%81%D0%BA%D0%BE%D0%B2)

**Comment by rominf** [comment]
@Alexey-Abakumkin, жжёшь. Поправил ошибки.
