### ISSUE TITLE
Имена модулей

### ISSUE THREAD

**Issue by rominf** [iu7-ray-teamwork/junkcraft#22]
Что за фигня с именами модулей?
`_SDL, _Image`?

Я попытался запустить, у меня не завелось: файл называется `_sdl.py`, а импортируется `_SDL`. Починил — завелось.

@yuri-kilochek, какой профит от `_CamelCase`-ного названия? Видимость? Это выглядит страшно.

Давай я всё переименую в нормальный `c_style`? Ну или хотя бы в `_c_style`.

**Comment by rominf** [comment]
```
__all__ = []
__all__ += ["Image"]
```

@yuri-kilochek not pythonic вообще. Я понимаю, что поздно возмущаться и я ни вообще кода не писал, но реально как-то мало хочется в таком стиле писать.

Тебя видимость смущает что ли?

```
We are all consenting adults here.
```

**Comment by yuri-kilochek** [comment]
_Image потому что типа имя класса. _SDL что префиксы в инфортируемых именах тоже капсом.

**Comment by rominf** [comment]
@yuri-kilochek 
Ну я это понимаю, просто нигде не используется так и см. PEP8:

```
Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability.
```

**Comment by yuri-kilochek** [comment]
Андерскоры  в начале у приватных модулей пакетов, их импортровать извне пакета никто не будет.

**Comment by yuri-kilochek** [comment]
Через **all** я делаю потому что без него экспортируются также все импортированные имена, альтернатива делать вещи вида import sys as _sys и все локальные имена тоже с  _ начинать. меньшее зло выбрано.

**Comment by rominf** [comment]
> Андерскоры в начале у приватных модулей пакетов, их импортровать извне пакета никто не будет.

Ну так и быть. Просто когда у тебя приложение, у тебя по сути все модули приватные. Я бы придерживался бы этого правила в случае с либами.

**Comment by yuri-kilochek** [comment]
Я делаю вид что пишу пакет engine как либу для себя. Потом его буду в другом пакете использовать.

**Comment by rominf** [comment]
> Через all я делаю потому что без него экспортируются также все импортированные имена, альтернатива делать вещи вида import sys as _sys

Какая разница, что экспортируется? Все (включая создателей стандартной либы) плевали на то, что пространство замусорено.

**Comment by yuri-kilochek** [comment]
И это ужасно. Из-за этого потом и возникают рекококомендации никогда не делать from X import \* и писать везде имя модуля и страдать.

**Comment by rominf** [comment]
Ну конечно, namespace-ы это же круто. В динамических языках (фигово анализируются, можно туда-сюда переменные объявлять и т.п.) объект `path` может оказаться чем угодно. А вот `os.path` не спутаешь. Ну а часто используемые классы или Qt-ные классы можно импортировать `from`-ом.
Ну ладно. Пофиг. Я считаю, что ты не прав, это un-pythonic, мучения с `__all__` того не стоят, но раз ты уже пишешь код, буду подстраиваться, если вдруг что.

**Comment by yuri-kilochek** [comment]
C path пример не убедительный, os.path это тоже модуль. А вот dirname оттуда например можно юзать и без квалификаторов. path это по сути набор методов от класса которого не существует, и которым приходится постоянно передавать строки. Был бы это класс с именем Path никакх проблем бы небыло (господа это таки осознали и сделали pathlib).
