### ISSUE TITLE
Записать soundtrack

### ISSUE THREAD

**Issue by rominf** [iu7-ray-teamwork/junkcraft#4]
Могу сыграть Star Wars на блок-флейте. Если осилю, то с гитарной партией.

**Comment by Alexey-Abakumkin** [comment]
Саундтрек можно поискать на сайтах со свободной лицензией: jamendo или soundcloud

**Comment by rominf** [comment]
Не true. Я хочу свой soundtrack)

**Comment by yuri-kilochek** [comment]
ненужно нам саундтрек, у нас сдаваться будет максимум чтото уровня пре-альфа

**Comment by Alexey-Abakumkin** [comment]
Согласен. Это пока лишние ненужные затраты времени. Можно закрывать
