### ISSUE TITLE
Нарисовать графику

### ISSUE THREAD

**Issue by rominf** [iu7-ray-teamwork/junkcraft#5]
На мой взгляд реально нарисовать что-то типа:
![](http://cdn.makeuseof.com/wp-content/uploads/2012/03/spacebattlesmac.jpg?bd76e7)
![](http://3.bp.blogspot.com/-jGC08Dy0zg8/U405cNq1-MI/AAAAAAAABqU/38d5rmV1S8Y/s1600/redfighter0006.png)

Может быть можно не рисовать, а собрать из кусков, но я что-то сомневаюсь.

**Comment by rominf** [comment]
Думаю, что графика должна быть векторная и корабли типа верхнего.

**Comment by yuri-kilochek** [comment]
да мы так угорим. простые битмапы с прозрачностью и норм

**Comment by yuri-kilochek** [comment]
Слишком широкий таск. Я бы его удалил но не понимаю как тут это сделать.
