### ISSUE TITLE
Выбрать графический framework

### ISSUE THREAD

**Issue by rominf** [iu7-ray-teamwork/junkcraft#6]
Вроде бы выбрали [PySDL2](https://bitbucket.org/marcusva/py-sdl2), но вдруг.

Информация для размышления:
http://en.wikipedia.org/wiki/List_of_game_engines
http://www.reddit.com/r/Python/comments/1z27fv/if_the_pyglet_community_is_dead_and_pygame_is_not/

**Comment by yuri-kilochek** [comment]
одобряю SDL2
